### PR TITLE
Pywren section fixes

### PR DESCRIPTION
**Pull request by gilv**
Various fixes to the PyWren related part. 
WIP

### CODE REVIEW

**Comment by gilv** [comment]
comments are welcome.
However WIP. Don't merge yet

**Comment by rhagarty** [comment]
Sorry - didn't see your WIP comment, so I reverted this PR.

**Comment by rhagarty** [comment]
@gilv - can re-submit this PR? I inadvertently merged it before noticing your "do not merge message".

BTW, please create a branch when working on a PR. It appears in this case your PR was based on a your local master version.

```
git checkout -b <branch-name>
git push origin <branch-name>
```
This creates a PR by comparing your branch to master.

**Comment by rhagarty** [comment]
@gilv - sorry for my confusion. Didn't realize that you had created a fork for your branch.

**Pull request merged**
